/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni202557201024;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Hype G12
 */
public class Dasboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dasboard.class.getName());
    private CardLayout cardLayout;

    /**
     * Creates new form Dasboard
     */
    public Dasboard() {
        initComponents();
        inisiasipanel();
    }
    
    void inisiasipanel() {
        cardLayout = (CardLayout)panelcontent.getLayout();
        panelcontent.add(new PanelDashboard(),"dashboard");
        panelcontent.add(new PanelJurusan(),"jurusan");
        panelcontent.add(new PanelGuru(),"guru");
        panelcontent.add(new PanelSiswa(),"siswa");
        panelcontent.add(new PanelKelas(),"kelas");
        panelcontent.add(new PanelAbout(),"about");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bguru = new javax.swing.JButton();
        bdashboard = new javax.swing.JButton();
        bjurusan = new javax.swing.JButton();
        bsiswa = new javax.swing.JButton();
        bkelas = new javax.swing.JButton();
        babout = new javax.swing.JButton();
        blogout = new javax.swing.JButton();
        panelcontent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI ALUMNI");

        panelsidebar.setBackground(new java.awt.Color(0, 153, 255));
        panelsidebar.setMinimumSize(new java.awt.Dimension(200, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-university-48.png"))); // NOI18N
        jLabel1.setText("Aloomni");

        bguru.setBackground(new java.awt.Color(0, 153, 255));
        bguru.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bguru.setForeground(new java.awt.Color(255, 255, 255));
        bguru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-teacher-20.png"))); // NOI18N
        bguru.setText("Guru");
        bguru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bguru.setIconTextGap(10);
        bguru.addActionListener(this::bguruActionPerformed);

        bdashboard.setBackground(new java.awt.Color(0, 153, 255));
        bdashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bdashboard.setForeground(new java.awt.Color(255, 255, 255));
        bdashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-dashboard-20.png"))); // NOI18N
        bdashboard.setText("Dashboard");
        bdashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdashboard.setIconTextGap(10);
        bdashboard.addActionListener(this::bdashboardActionPerformed);

        bjurusan.setBackground(new java.awt.Color(0, 153, 255));
        bjurusan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bjurusan.setForeground(new java.awt.Color(255, 255, 255));
        bjurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-university-20.png"))); // NOI18N
        bjurusan.setText("Jurusan");
        bjurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bjurusan.setIconTextGap(10);
        bjurusan.addActionListener(this::bjurusanActionPerformed);

        bsiswa.setBackground(new java.awt.Color(0, 153, 255));
        bsiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bsiswa.setForeground(new java.awt.Color(255, 255, 255));
        bsiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-student-20 - Salin.png"))); // NOI18N
        bsiswa.setText("Siswa");
        bsiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bsiswa.setIconTextGap(10);
        bsiswa.addActionListener(this::bsiswaActionPerformed);

        bkelas.setBackground(new java.awt.Color(0, 153, 255));
        bkelas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bkelas.setForeground(new java.awt.Color(255, 255, 255));
        bkelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-class-20.png"))); // NOI18N
        bkelas.setText("Kelas");
        bkelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkelas.setIconTextGap(10);
        bkelas.addActionListener(this::bkelasActionPerformed);

        babout.setBackground(new java.awt.Color(0, 153, 255));
        babout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        babout.setForeground(new java.awt.Color(255, 255, 255));
        babout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-about-20.png"))); // NOI18N
        babout.setText("About");
        babout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        babout.setIconTextGap(10);
        babout.addActionListener(this::baboutActionPerformed);

        blogout.setBackground(new java.awt.Color(0, 153, 255));
        blogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        blogout.setForeground(new java.awt.Color(255, 255, 255));
        blogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-logout-20.png"))); // NOI18N
        blogout.setText("Logout");
        blogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blogout.setIconTextGap(10);
        blogout.addActionListener(this::blogoutActionPerformed);

        javax.swing.GroupLayout panelsidebarLayout = new javax.swing.GroupLayout(panelsidebar);
        panelsidebar.setLayout(panelsidebarLayout);
        panelsidebarLayout.setHorizontalGroup(
            panelsidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelsidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(bjurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bguru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bkelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(babout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelsidebarLayout.setVerticalGroup(
            panelsidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsidebarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(bdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bguru, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(babout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        getContentPane().add(panelsidebar, java.awt.BorderLayout.LINE_START);

        panelcontent.setBackground(new java.awt.Color(255, 255, 255));
        panelcontent.setMinimumSize(new java.awt.Dimension(600, 800));
        panelcontent.setPreferredSize(new java.awt.Dimension(600, 1000));
        panelcontent.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelcontent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguruActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelcontent, "guru");
    }//GEN-LAST:event_bguruActionPerformed

    private void bsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsiswaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelcontent, "siswa");
    }//GEN-LAST:event_bsiswaActionPerformed

    private void bdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdashboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelcontent, "dashboard ");
    }//GEN-LAST:event_bdashboardActionPerformed

    private void bjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjurusanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelcontent, "jurusan");
    }//GEN-LAST:event_bjurusanActionPerformed

    private void bkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkelasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelcontent, "kelas");
    }//GEN-LAST:event_bkelasActionPerformed

    private void baboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelcontent, "about");
    }//GEN-LAST:event_baboutActionPerformed

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(null,
                "Apakah Anda Yakin ingin keluar?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        
        switch(pilihan){
           case JOptionPane.YES_OPTION:
               dispose();
               new Framelogin().setVisible(true);
               break;
            case JOptionPane.NO_OPTION:
                break;
                default:
                    break;
    
        }
    }//GEN-LAST:event_blogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    try {
        UIManager.put("Button.borderWidth", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dasboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton babout;
    private javax.swing.JButton bdashboard;
    private javax.swing.JButton bguru;
    private javax.swing.JButton bjurusan;
    private javax.swing.JButton bkelas;
    private javax.swing.JButton blogout;
    private javax.swing.JButton bsiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelcontent;
    private javax.swing.JPanel panelsidebar;
    // End of variables declaration//GEN-END:variables
}
