/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201024;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hype G12
 */
public class PanelJurusan extends javax.swing.JPanel {

    /**
     * Creates new form PanelJurusan
     */
    public PanelJurusan() {
        initComponents();
        reset();
        load_tabel_jurusan();
    }
    
    void reset(){
        // Kosongkan isi text field kode jurusan
        tKodeJurusan.setText(null);

        // Aktifkan kembali text field kode jurusan agar bisa diedit
        tKodeJurusan.setEditable(true);

        // Kosongkan isi text field nama jurusan
        tNamaJurusan.setText(null);
    }
    
    void load_tabel_jurusan(){
    // Membuat objek model tabel baru
    DefaultTableModel model = new DefaultTableModel();
    
    // Menambahkan kolom ke dalam model tabel
    
    // Kolom pertama untuk kode jurusan
    model.addColumn("Kode Jurusan");
    // Kolom kedua untuk nama jurusan
    model.addColumn("Nama Jurusan");
    
    // Query SQL untuk mengambil semua data dari tabel jurusan
    String sql = "SELECT * FROM jurusan";
    
        try {
            // membukan koneksi ke databases
            Connection con = koneksi.konek();
            //membuat statement untuk menjalankan quwry
            Statement st = con.createStatement();
            //menjalankan quwery dan menyimpanya hasilnya dalam Resultset
            ResultSet rs = st.executeQuery(sql);
            //melakukan iterasi untuk setiap baris data hasil query
            while (rs.next()) {
                //mengambil data kode jur
                String kodeJurusan = rs.getString("kode_jur");
                //mengambil data kolom nama_jurusan 
                String namaJurusan = rs.getString("nama_jurusan");
                //membuat array baris data satu baris
                Object[] baris = {kodeJurusan, namaJurusan};
                //menambahkan array baris ke dalam model tabel
                model.addRow(baris);                
            }
        } catch (SQLException sQLException) {
            //menampilkan pesan error jika gagal mengambil data dari database
            JOptionPane.showMessageDialog(null, "Gagal mengambil data ");
        }
    //Menampilkan model yang sudah diisi ke dalam tabel gui
    tblJurusan.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tKodeJurusan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tNamaJurusan = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJurusan = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 20, true));
        setMinimumSize(new java.awt.Dimension(953, 691));
        setPreferredSize(new java.awt.Dimension(953, 691));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(100, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Jurusan");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jLabel1.setMaximumSize(new java.awt.Dimension(87, 18));
        jLabel1.setMinimumSize(new java.awt.Dimension(87, 18));
        jLabel1.setPreferredSize(new java.awt.Dimension(87, 18));
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-multiply-20.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel4.add(jLabel2, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("kode jurusan");

        tKodeJurusan.setText("jTextField1");

        jLabel4.setText("Nama  jurusan");

        tNamaJurusan.setText("jTextField1");

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-trash-20.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnTambah.setBackground(new java.awt.Color(0, 204, 0));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-20.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnReset.setBackground(new java.awt.Color(0, 102, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-reset-20 (1).png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnUbah.setBackground(new java.awt.Color(255, 153, 51));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-write-20.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tKodeJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tNamaJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tKodeJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNamaJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 20, true));
        jPanel2.setLayout(new java.awt.CardLayout());

        tblJurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJurusanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblJurusan);

        jPanel2.add(jScrollPane2, "card2");

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblJurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJurusanMouseClicked
        // TODO add your handling code here:
   // Ambil indeks baris yang diklik oleh pengguna di tabel tblJurusan
int barisYangDipilih = tblJurusan.rowAtPoint(evt.getPoint());

// Ambil nilai dari kolom pertama (indeks 0) pada baris yang dipilih, yaitu 'kode_ju
String kodeJurusan = tblJurusan.getValueAt(barisYangDipilih, 0).toString();

// Ambil nilai dari kolom kedua (indeks 1) pada baris yang dipilih, yaitu 'nama_juru
String namaJurusan = tblJurusan.getValueAt(barisYangDipilih, 1).toString();

// Tampilkan kode jurusan di text field tKodeJurusan
tKodeJurusan.setText(kodeJurusan);

// Nonaktifkan pengeditan pada text field kode jurusan (agar tidak bisa diubah)
tKodeJurusan.setEditable(false);

// Tampilkan nama jurusan di text field tNamaJurusan
tNamaJurusan.setText(namaJurusan);     
        
    }//GEN-LAST:event_tblJurusanMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        // Ambil input dari text field tKodeJurusan dan simpan ke variabel kodeJurusan
String kodeJurusan = tKodeJurusan.getText();

// Ambil input dari text field tNamaJurusan dan simpan ke variabel namaJurusan
String namaJurusan = tNamaJurusan.getText();

// Query SQL untuk menyisipkan data ke tabel jurusan
String sql = "INSERT INTO jurusan(kode_jur,nama_jurusan) VALUES(?,?)";
try {
    // Buat koneksi ke database menggunakan method konek() dari class koneksi
    Connection conn = koneksi.konek();

    // Siapkan query SQL untuk dieksekusi dengan parameter
    PreparedStatement ps = conn.prepareStatement(sql);

    // Isi parameter pertama (?) dengan kode jurusan
    ps.setString(1, kodeJurusan);

    // Isi parameter kedua (?) dengan nama jurusan
    ps.setString(2, namaJurusan);

    // Jalankan query untuk menyimpan data ke database
    ps.execute();

    // Tampilkan pesan bahwa data berhasil disimpan
    JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
} catch (SQLException sqlException) {
    // Jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
    JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
}

// Panggil method untuk memuat ulang data pada tabel jurusan
load_tabel_jurusan();

// Panggil method untuk mereset atau mengosongkan inputan
reset();


    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
 // Ambil input dari text field tKodeJurusan dan simpan ke variabel kodeJurusan
String kodeJurusan = tKodeJurusan.getText();

// Ambil input dari text field tNamaJurusan dan simpan ke variabel namaJurusan
String namaJurusan = tNamaJurusan.getText();

// Query SQL untuk mengubah data pada tabel jurusan
String sql = "UPDATE jurusan SET nama_jurusan=? WHERE kode_jur=?";

try {
    // Buat koneksi ke database menggunakan method konek() dari class koneksi
    Connection conn = koneksi.konek();

    // Siapkan query SQL untuk dieksekusi dengan parameter
    PreparedStatement ps = conn.prepareStatement(sql);

    // Isi parameter pertama (?) dengan kode jurusan
    ps.setString(1, namaJurusan);

    // Isi parameter kedua (?) dengan nama jurusan
    ps.setString(2, kodeJurusan);

    // Jalankan query untuk menyimpan data ke database
    ps.execute();

    // Tampilkan pesan bahwa data berhasil diubah
    JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
} catch (SQLException sqlException) {
    // Jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
    JOptionPane.showMessageDialog(null, "Data gagal diubah!");
}

// Panggil method untuk memuat ulang data pada tabel jurusan
load_tabel_jurusan();

// Panggil method untuk mereset atau mengosongkan inputan
reset();

    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
// Ambil input dari text field tKodeJurusan dan simpan ke variabel kodeJurusan
String kodeJurusan = tKodeJurusan.getText();

// Query SQL untuk menghapus data pada tabel jurusan berdasarkan kode_jur
String sql = "DELETE FROM jurusan WHERE kode_jur=?";

try {
    // Buat koneksi ke database menggunakan method konek() dari class koneksi
    Connection conn = koneksi.konek();

    // Siapkan query SQL untuk dieksekusi dengan parameter
    PreparedStatement ps = conn.prepareStatement(sql);

    // Isi parameter pertama (?) dengan kode jurusan
    ps.setString(1, kodeJurusan);

    // Jalankan query untuk menyimpan data ke database
    ps.execute();

    // Tampilkan pesan bahwa data berhasil dihapus
    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
} catch (SQLException sQLException) {
    // Jika terjadi kesalahan saat menghapus data, tampilkan pesan gagal
    JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
}

// Panggil method untuk memuat ulang data pada tabel jurusan
load_tabel_jurusan();

// Panggil method untuk mereset atau mengosongkan inputan
reset();

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tKodeJurusan;
    private javax.swing.JTextField tNamaJurusan;
    private javax.swing.JTable tblJurusan;
    // End of variables declaration//GEN-END:variables

    private static class rs {

        public rs() {
        }
    }
}
