/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201024;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author Hype G12
 */
public class PanelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
        isiJumlahDataDasbor();
    }
private void isiJumlahDataDasbor() {
    // Membuka koneksi ke database
    Connection conn = koneksi.konek();

    try {
        // Mengambil jumlah jurusan dari tabel jurusan
        String sqlJurusan = "SELECT COUNT(*) AS jumlah FROM jurusan";
        Statement psJurusan = conn.createStatement();
        ResultSet rsJurusan = psJurusan.executeQuery(sqlJurusan);

        // Jika hasil query ada, ambil dan tampilkan ke label jumlah jurusan
        if (rsJurusan.next()) {
            int jumlah = rsJurusan.getInt("jumlah");
            tJumlahJurusan.setText(String.valueOf(jumlah));
        }

        // Mengambil jumlah guru dari tabel guru
        String sqlGuru = "SELECT COUNT(*) AS jumlah FROM guru";
        Statement psGuru = conn.createStatement();
        ResultSet rsGuru = psGuru.executeQuery(sqlGuru);

        // Jika hasil query ada, ambil dan tampilkan ke label jumlah guru
        if (rsGuru.next()) {
            int jumlah = rsGuru.getInt("jumlah");
            tJumlahGuru.setText(String.valueOf(jumlah));
        }

        // Mengambil jumlah siswa dari tabel siswa
        String sqlSiswa = "SELECT COUNT(*) AS jumlah FROM siswa";
        Statement psSiswa = conn.createStatement();
        ResultSet rsSiswa = psSiswa.executeQuery(sqlSiswa);

        // Jika hasil query ada, ambil dan tampilkan ke label jumlah siswa
        if (rsSiswa.next()) {
            int jumlah = rsSiswa.getInt("jumlah");
            tJumlahSiswa.setText(String.valueOf(jumlah));
        }

        // Mengambil jumlah kelas dari tabel kelas
        String sqlKelas = "SELECT COUNT(*) AS jumlah FROM kelas";
        Statement psKelas = conn.createStatement();
        ResultSet rsKelas = psKelas.executeQuery(sqlKelas);

        // Jika hasil query ada, ambil dan tampilkan ke label jumlah kelas
        if (rsKelas.next()) {
            int jumlah = rsKelas.getInt("jumlah");
            tJumlahKelas.setText(String.valueOf(jumlah));
        }

    } catch (SQLException e) {
        // Menampilkan pesan di konsol jika terjadi error saat mengambil data
        System.err.println("Gagal mengambil jumlah data");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tJumlahJurusan = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tJumlahGuru = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tJumlahSiswa = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tJumlahKelas = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 20, true));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(906, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(906, 150));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jumlah Jurusan");
        jLabel2.setMaximumSize(new java.awt.Dimension(46, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(46, 30));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(46, 30));
        jPanel3.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        tJumlahJurusan.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahJurusan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tJumlahJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahJurusan.setText("JJ");
        tJumlahJurusan.setMaximumSize(new java.awt.Dimension(124, 42));
        tJumlahJurusan.setMinimumSize(new java.awt.Dimension(124, 42));
        tJumlahJurusan.setOpaque(true);
        tJumlahJurusan.setPreferredSize(new java.awt.Dimension(124, 42));
        jPanel3.add(tJumlahJurusan, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2);

        jPanel5.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setMinimumSize(new java.awt.Dimension(906, 150));
        jPanel6.setPreferredSize(new java.awt.Dimension(906, 150));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(51, 153, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jumlah Guru");
        jLabel3.setMaximumSize(new java.awt.Dimension(46, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(46, 30));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(46, 30));
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        tJumlahGuru.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahGuru.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tJumlahGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahGuru.setText("JG");
        tJumlahGuru.setMaximumSize(new java.awt.Dimension(124, 42));
        tJumlahGuru.setMinimumSize(new java.awt.Dimension(124, 42));
        tJumlahGuru.setOpaque(true);
        tJumlahGuru.setPreferredSize(new java.awt.Dimension(124, 42));
        jPanel6.add(tJumlahGuru, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel5);

        jPanel7.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setMinimumSize(new java.awt.Dimension(906, 150));
        jPanel8.setPreferredSize(new java.awt.Dimension(906, 150));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(51, 153, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Kelas");
        jLabel5.setMaximumSize(new java.awt.Dimension(46, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(46, 30));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(46, 30));
        jPanel8.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        tJumlahSiswa.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahSiswa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tJumlahSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahSiswa.setText("JK");
        tJumlahSiswa.setMaximumSize(new java.awt.Dimension(124, 42));
        tJumlahSiswa.setMinimumSize(new java.awt.Dimension(124, 42));
        tJumlahSiswa.setOpaque(true);
        tJumlahSiswa.setPreferredSize(new java.awt.Dimension(124, 42));
        jPanel8.add(tJumlahSiswa, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel7);

        jPanel9.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setMinimumSize(new java.awt.Dimension(906, 150));
        jPanel10.setPreferredSize(new java.awt.Dimension(906, 150));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(51, 153, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jumlah Siswa");
        jLabel7.setMaximumSize(new java.awt.Dimension(46, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(46, 30));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(46, 30));
        jPanel10.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        tJumlahKelas.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahKelas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tJumlahKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahKelas.setText("JS");
        tJumlahKelas.setMaximumSize(new java.awt.Dimension(124, 42));
        tJumlahKelas.setMinimumSize(new java.awt.Dimension(124, 42));
        tJumlahKelas.setOpaque(true);
        tJumlahKelas.setPreferredSize(new java.awt.Dimension(124, 42));
        jPanel10.add(tJumlahKelas, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel9);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel tJumlahGuru;
    private javax.swing.JLabel tJumlahJurusan;
    private javax.swing.JLabel tJumlahKelas;
    private javax.swing.JLabel tJumlahSiswa;
    // End of variables declaration//GEN-END:variables
}
